apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Kubernetes Infrastructure Management
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  # Allow everything
  clusterResourceWhitelist:
  - '*'
  # Allow all namespaced-scoped
  namespaceResourceBlacklist: []
  # 
  namespaceResourceWhitelist:
  - '*' 
  roles: []
